[features]
seeds = false
skip-lint = false
[programs.localnet]
drift_adaptor = "6tTgCX22MLxWBDf4h6yPNEqnshhJDfwetqBdLAfcp2Xi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ming/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
